update baru bugs 2

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -35,29 +35,28 @@ jobs:
           cd temp
           cordova build android
 
-            - name: Copy APK to repo
+      - name: Copy APK to repo
         run: |
-          echo "=== SEARCHING APK ==="
+          echo "=== SEARCH APK ==="
           find temp -type f -name "*.apk"
 
           APK_PATH=$(find temp -type f -name "*.apk" | head -n 1)
 
           if [ -z "$APK_PATH" ]; then
-            echo "❌ APK NOT FOUND"
+            echo " APK NOT FOUND"
             exit 1
           fi
 
-          echo "✅ APK FOUND AT: $APK_PATH"
+          echo " APK FOUND: $APK_PATH"
 
           mkdir -p apk
           cp "$APK_PATH" apk/Absensi-RPL-Muhtiga.apk
           ls -lah apk
-
 
       - name: Commit APK to repository
         run: |
           git config user.name "github-actions"
           git config user.email "actions@github.com"
           git add apk/Absensi-RPL-Muhtiga.apk
-          git commit -m "Update APK Absensi RPL Muhtiga" || echo "No changes to commit"
+          git commit -m "Update APK Absensi RPL Muhtiga" || echo "No changes"
           git push
