update apk to repository langsung

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -35,12 +35,24 @@ jobs:
           cd temp
           cordova build android
 
-      - name: Copy APK to repo
+            - name: Copy APK to repo
         run: |
+          echo "=== SEARCHING APK ==="
+          find temp -type f -name "*.apk"
+
+          APK_PATH=$(find temp -type f -name "*.apk" | head -n 1)
+
+          if [ -z "$APK_PATH" ]; then
+            echo "❌ APK NOT FOUND"
+            exit 1
+          fi
+
+          echo "✅ APK FOUND AT: $APK_PATH"
+
           mkdir -p apk
-          APK_PATH=$(find temp -name "*.apk" | head -n 1)
           cp "$APK_PATH" apk/Absensi-RPL-Muhtiga.apk
           ls -lah apk
+
 
       - name: Commit APK to repository
         run: |
